### ISSUE TITLE
noflo builder does not produce a working js file

### ISSUE THREAD

**Issue by thenikso** [noflo/noflo.github.io#39]
The builded `noflo.js` at http://noflojs.org/download/ does not work when included with the instructions included in the page.

Apparently it does not include the selected libraries and aliases `.coffee` files instead of `.js`

**Comment by jonnor** [comment]
Duplicate of https://github.com/noflo/noflo/issues/288
Keeping open as we need to fix website (this repo).

**Comment by bergie** [comment]
The page is gone now, we're using NPM and webpack instead. See http://bergie.iki.fi/blog/noflo-webpack/
