### ISSUE TITLE
Broken HTTPS/SSL configuration

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo.github.io#61]
https://noflojs.org does not work, fails with a certificate error because the cert is for `*.github.com`.

This is especially problematic because we host software on this domain, ie for `noflo-browser` builds used in Flowhub and other places. These cannot be loaded on a HTTPS site, and for HTTP can be intercepted without detection.

**Comment by bergie** [comment]
Fixed: https://noflojs.org/
