### ISSUE TITLE
Build on Travis CI then push to Github Pages 

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo.github.io#67]
Right now Github Pages does the page build. This means we don't get notified about failures until we merge to master, when its already too late. It also limits what we can use to what gh-pages support, and requires checking in intermediate/generated data to the git repo.

**Comment by jonnor** [comment]
Generated files having to be committed to git also means that Greenkeeper changes for updates to dependenies won't regenerate the docs and a developer must do it manually on the commandline.

**Comment by bergie** [comment]
Yes, good idea
